apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 80
    name: web
    targetPort: 4100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        version: "1.0"
        track: stable
    spec:
      containers:
      - name: frontend
        image: evgeniybog/interview-devops-frontend:1.0
        ports:
        - containerPort: 4100
        env:
        - name: REACT_APP_API_ROOT
          value: http://159.89.221.179:8080