version: '3.7'

services:
  frontend:
    build: ./frontend
    image: mirshann/interview-devops/frontend:1.0
    environment:
      - "REACT_APP_API_ROOT=http://localhost:8080"
    ports:
      - "4100:4100"

  # backend.v1:
  #   build: ./backend.v1
  #   image: mirshann/interview-devops/backend:1.0
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./data:/app/data

  backend.v2:
    build: ./backend.v2
    image: mirshann/interview-devops/backend:2.0
    ports:
      -  "8080:8080"
    volumes:
      - ./data:/app/data